#! /bin/bash


tty1-print -n "Looking for microphones...  "

timeout=30
found=0
count=$((timeout * 2))
progress='-\|/'
length=${#progress}

for ((i = 0; i < $count; i++)); do
  mics=`arecord --list-devices | grep '^card' | wc -l`
  if [ "$mics" -gt 0 ]; then
    found=1;
    break;
  fi
  pos=$((i % length))
  char="${progress:pos:1}"
  tty1-print -ne "\b$char"
  sleep 0.5
done
tty1-print -e "\b "


if [ "$found" -eq 1 ]; then
  tty1-print -e "\e[0;32mSUCCESS\033[0m: $mics microphone(s) detected!"
  tty1-print -e "Starting Ultrastar, please wait..."
  exit 0
else
  tty1-print -e "\e[0;31mERROR\033[0m: No microphones detected!"
  tty1-print -e "Ultrastar may crash unexpectedly if no microphones are connected when playing a song."
  tty1-print -e "Please consider connecting \e[0;31mat least one microphone\033[0m before starting Ultrastar."

  timeout=10
  for ((i = $timeout; i >= 0; i--)); do
    tty1-print -ne "Ultrastar will start in $timeout seconds...\033[0K\r"
    sleep 1
  done
  tty1-print -e ""

  tty1-print "Starting Ultrastar, please wait..."
  exit 1
fi
